[package]
version = "0.1.0"

# These fields are used primarily for display in the extension browser UI.
title = "Aerosim Omniverse Extension"
description = "Omniverse extension to connect with the AeroSim simulator."
category = "Aerosim"
keywords = ["aerosim", "cpp"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["AeroSim"]

[dependencies]
"omni.usd" = {}
"cesium.omniverse"={}

# Define the Python modules that this extension provides.
# C++ only extensions need this just so tests don't fail.
[[python.module]]
name = "aerosim.omniverse.extension"

# Define the C++ plugins that this extension provides.
[[native.plugin]]
path = "bin/*.plugin"

# Define the documentation that will be generated for this extension.
[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
cpp_api = [
    "include/aerosim/omniverse/extension/IAerosimConnector.h",
]
[settings]
app.useFabricSceneDelegate = true
app.usdrt.scene_delegate.enableProxyCubes = false
app.usdrt.scene_delegate.geometryStreaming.enabled = false
